apiVersion: v1
kind: Pod
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Deep Insights
    categories: Security
    certified: "false"
    cni.projectcalico.org/containerID: 07b1897699ace3d9fa3e8883c5fdc78c706c0ec07adc6c0faf8ac534cff8b956
    cni.projectcalico.org/podIP: 172.21.7.139/32
    cni.projectcalico.org/podIPs: 172.21.7.139/32
    containerImage: quay.io/redhat-cop/cert-utils-operator@sha256:0290e7b2800a5aa8eb57b0268908f2a20a93b16403c76df4c61021048161d6ff
    createdAt: "2024-01-23T12:29:04Z"
    description: Set of utilities for TLS certificates
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.21.7.139"
          ],
          "default": true,
          "dns": {}
      }]
    olm.operatorGroup: cert-utils-operator
    olm.operatorNamespace: cert-utils-operator
    olm.targetNamespaces: ""
    openshift.io/scc: restricted-v2
    operatorframework.io/cluster-monitoring: "true"
    operatorframework.io/properties: '{"properties":[{"type":"olm.package","value":{"packageName":"cert-utils-operator","version":"1.3.12"}}]}'
    operatorframework.io/suggested-namespace: cert-utils-operator
    operators.openshift.io/infrastructure-features: '["Disconnected"]'
    operators.operatorframework.io/builder: operator-sdk-v1.8.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: https://github.com/redhat-cop/cert-utils-operator
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    support: Best Effort
  creationTimestamp: "2024-06-11T14:14:42Z"
  generateName: cert-utils-operator-controller-manager-7bb98bdd74-
  labels:
    control-plane: cert-utils-operator
    pod-template-hash: 7bb98bdd74
  name: cert-utils-operator-controller-manager-7bb98bdd74-qgkhw
  namespace: cert-utils-operator
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: cert-utils-operator-controller-manager-7bb98bdd74
    uid: b5ab5ae3-b24a-4c19-a3d5-5806e6a73c13
  resourceVersion: "127997749"
  uid: 806208de-8a9e-4a54-9573-25ee7293c22e
spec:
  containers:
  - args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --tls-cert-file=/etc/certs/tls/tls.crt
    - --tls-private-key-file=/etc/certs/tls/tls.key
    env:
    - name: OPERATOR_CONDITION_NAME
      value: cert-utils-operator.v1.3.12
    image: quay.io/redhat-cop/kube-rbac-proxy@sha256:c68135620167c41e3d9f6c1d2ca1eb8fa24312b86186d09b8010656b9d25fb47
    imagePullPolicy: IfNotPresent
    name: kube-rbac-proxy
    ports:
    - containerPort: 8443
      name: https
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000690000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/certs/tls
      name: tls-cert
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sl8kq
      readOnly: true
  - args:
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=127.0.0.1:8080
    - --leader-elect
    command:
    - /manager
    env:
    - name: OPERATOR_CONDITION_NAME
      value: cert-utils-operator.v1.3.12
    image: quay.io/redhat-cop/cert-utils-operator@sha256:0290e7b2800a5aa8eb57b0268908f2a20a93b16403c76df4c61021048161d6ff
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 1
    name: manager
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
        memory: 20Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000690000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sl8kq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: controlplane-imagepullsecret
  - name: controller-manager-dockercfg-4phlf
  nodeName: 192.168.192.17
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000690000
    seLinuxOptions:
      level: s0:c26,c20
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: controller-manager
  serviceAccountName: controller-manager
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: tls-cert
    secret:
      defaultMode: 420
      secretName: cert-utils-operator-certs
  - name: kube-api-access-sl8kq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T14:14:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T14:15:22Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T14:15:22Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T14:14:42Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://1c7391f2d49c85183e862e68e4bf1dad8921ea37ed8e0c5cd78e3fbc81af4e27
    image: quay.io/redhat-cop/kube-rbac-proxy@sha256:c68135620167c41e3d9f6c1d2ca1eb8fa24312b86186d09b8010656b9d25fb47
    imageID: quay.io/redhat-cop/kube-rbac-proxy@sha256:8ac4596bae29a6956d9e3a6688e38fc82ea0dbab877ab554096d54f80f0252a3
    lastState: {}
    name: kube-rbac-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-11T14:15:13Z"
  - containerID: cri-o://f1bf065dc0e417b2d6eda283e89a87edcef620a66589edf6bbb040ad4d395520
    image: quay.io/redhat-cop/cert-utils-operator@sha256:0290e7b2800a5aa8eb57b0268908f2a20a93b16403c76df4c61021048161d6ff
    imageID: quay.io/redhat-cop/cert-utils-operator@sha256:0290e7b2800a5aa8eb57b0268908f2a20a93b16403c76df4c61021048161d6ff
    lastState: {}
    name: manager
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-11T14:15:16Z"
  hostIP: 192.168.192.17
  phase: Running
  podIP: 172.21.7.139
  podIPs:
  - ip: 172.21.7.139
  qosClass: Burstable
  startTime: "2024-06-11T14:14:41Z"
