apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: a54c4efe6a2e7423cd138c1c4446b58529bdd498ea4190dbf90ff33ace3bc239
    cni.projectcalico.org/podIP: 172.21.221.75/32
    cni.projectcalico.org/podIPs: 172.21.221.75/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.21.221.75"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-06-11T13:28:56Z"
  generateName: cloudrock-nw-controller-77b976976c-
  labels:
    app: cloudrock-nw-controller
    by-squad: mcsp-controlplane
    for-product: all
    pod-template-hash: 77b976976c
  name: cloudrock-nw-controller-77b976976c-ps9hn
  namespace: cloudrock-controller
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: cloudrock-nw-controller-77b976976c
    uid: 2e067fea-e496-4fc0-a302-5003cd8b8cbd
  resourceVersion: "127924995"
  uid: cde20e4c-1d27-4b62-a47c-8829b9082676
spec:
  automountServiceAccountToken: true
  containers:
  - env:
    - name: CONTROLLER_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: CONTROLLER_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: CONTROLLER_POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: AWS_REGION
      value: us-east-1
    - name: OPERATOR_NAME
      value: cloudrock-nw-controller
    - name: ROSA_TOKEN_PATH
      value: /secrets/rosatoken
    - name: CR_CFG_FILEPATH
      value: /config/embed/config.yaml
    - name: ENABLE_WEBHOOKS
      value: "true"
    - name: SLACK_BOT_TOKEN_PATH
      value: /secrets/slackbottoken
    - name: SLACK_CHANNEL_ID_PATH
      value: /secrets/slackchannelid
    - name: PULL_SECRET_PATH
      value: /secrets/pullsecret
    image: icr.io/cr-controlplane-release/cloudrock-nw-controller:1.2.3-amd64
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 8081
      timeoutSeconds: 5
    name: cloudrock-controller
    ports:
    - containerPort: 9443
      name: webhook-server
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      initialDelaySeconds: 12
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 8081
      timeoutSeconds: 6
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000680000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /secrets
      mountPropagation: None
      name: cloudrock-controller-secrets
      readOnly: true
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      mountPropagation: None
      name: cert
      readOnly: true
    - mountPath: /.aws
      mountPropagation: None
      name: aws-credential
    - mountPath: /.config
      mountPropagation: None
      name: ocm
    - mountPath: /tokens
      mountPropagation: None
      name: admin-tokens
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-crz5j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: controlplane-imagepullsecret
  - name: cloudrock-controller-dockercfg-r6wsp
  nodeName: 192.168.194.14
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000680000
    runAsNonRoot: true
    seLinuxOptions:
      level: s0:c26,c15
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: cloudrock-controller
  serviceAccountName: cloudrock-controller
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: cert
    secret:
      defaultMode: 420
      optional: false
      secretName: webhook-server-cert
  - name: cloudrock-controller-secrets
    secret:
      defaultMode: 420
      optional: false
      secretName: cloudrock-controller-secrets
  - emptyDir:
      sizeLimit: 1Mi
    name: aws-credential
  - emptyDir:
      sizeLimit: 1Mi
    name: ocm
  - emptyDir:
      sizeLimit: 1Mi
    name: admin-tokens
  - name: kube-api-access-crz5j
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T13:28:55Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T13:29:25Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T13:29:25Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T13:28:56Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://6264c16a4888f5ad71b99722efca47d421a360a43453d73f75ac28b0948e3e52
    image: icr.io/cr-controlplane-release/cloudrock-nw-controller:1.2.3-amd64
    imageID: icr.io/cr-controlplane-release/cloudrock-nw-controller@sha256:87c92f70ec963065bda18761c3b54edce3adda2a36dc8e99fa8c7563b6483528
    lastState: {}
    name: cloudrock-controller
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-11T13:29:11Z"
  hostIP: 192.168.194.14
  phase: Running
  podIP: 172.21.221.75
  podIPs:
  - ip: 172.21.221.75
  qosClass: Burstable
  startTime: "2024-06-11T13:28:55Z"
